spring.application.name=afyasoft
# DataSource
spring.datasource.generate-unique-name=false
spring.datasource.name=afryasoft

# SQL init
spring.sql.init.mode=always
spring.sql.init.platform=postgresql

# Postgresql
spring.datasource.jdbc-url=jdbc:postgresql://localhost:5432/afryasoft
spring.datasource.username=postgres
spring.datasource.password=IC@reJ@va
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.auto_quote_keyword=true

jwt.key=5efcc35635779cbcc6efade791d96cc8f0b77a5b7e7281a43354923872a273300b633681b14fd1ad4ee0f6027694fbce7eb8ba4c1f3f00dd3b4454e13d1c6807
remember.key=cce9494c-fc77-4557-952d-e4b199da05fc

spa.host.url=http://localhost:5173

debug=true